/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201706201043.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * The interface provies APIs to perform calculator operations * author: 
 * Module Owner Name
 */
#include <v1/SimpleCalculator/CalculatorInterface/CalculatorDBusProxy.hpp>

namespace v1 {
namespace SimpleCalculator {
namespace CalculatorInterface {

std::shared_ptr<CommonAPI::DBus::DBusProxy> createCalculatorDBusProxy(
    const CommonAPI::DBus::DBusAddress &_address,
    const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection) {
    return std::make_shared< CalculatorDBusProxy>(_address, _connection);
}

void initializeCalculatorDBusProxy() {
     CommonAPI::DBus::Factory::get()->registerProxyCreateMethod(
        Calculator::getInterface(),
        &createCalculatorDBusProxy);
}

INITIALIZER(registerCalculatorDBusProxy) {
    CommonAPI::DBus::Factory::get()->registerInterface(initializeCalculatorDBusProxy);
}

CalculatorDBusProxy::CalculatorDBusProxy(
    const CommonAPI::DBus::DBusAddress &_address,
    const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection)
    :   CommonAPI::DBus::DBusProxy(_address, _connection)
,        calattribute_(*this, "onCalattributeAttributeChanged", "setCalattributeAttribute", "i", "getCalattributeAttribute", static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr))
,        operation_status_(*this, "operation_status", "u", std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)))
{
}

      CalculatorDBusProxy::CalattributeAttribute& CalculatorDBusProxy::getCalattributeAttribute() {
          return calattribute_;
      }

CalculatorDBusProxy::Operation_statusEvent& CalculatorDBusProxy::getOperation_statusEvent() {
    return operation_status_;
}

    /*
     * description: 
     * Perform add operation.
     * (at)Return add result.
     */
    void CalculatorDBusProxy::add(const uint32_t &_param1, const uint32_t &_param2, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_param1(_param1, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_param2(_param2, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_result(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment >,
            CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint32_t,CommonAPI::DBus::IntegerDeployment>
            >
            >::callMethodWithReply(
        *this,
        "add",
        "uu",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param1, deploy_param2,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::addAsync(const uint32_t &_param1, const uint32_t &_param2, AddAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_param1(_param1, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_param2(_param2, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_result(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment >,
            CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint32_t,CommonAPI::DBus::IntegerDeployment>
            >
            >::callMethodAsync(
        *this,
        "add",
        "uu",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param1, deploy_param2,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform divide operation.
     * (at)Return add result.
     */
    void CalculatorDBusProxy::division(const float &_a, const float &_b, CommonAPI::CallStatus &_internalCallStatus, Calculator::DIVISION_ERROR &_error, float &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::DIVISION_ERROR, CommonAPI::EmptyDeployment> deploy_error(static_cast< CommonAPI::EmptyDeployment * >(nullptr));
        CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_a(_a, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_b(_b, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< float, CommonAPI::EmptyDeployment >,
            CommonAPI::Deployable< float, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::DIVISION_ERROR, CommonAPI::EmptyDeployment>,
            CommonAPI::Deployable< float,CommonAPI::EmptyDeployment>
            >
            >::callMethodWithReply(
        *this,
        "division",
        "dd",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_a, deploy_b,
_internalCallStatus,
deploy_error,
deploy_result);
_error = deploy_error.getValue();
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::divisionAsync(const float &_a, const float &_b, DivisionAsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::DIVISION_ERROR, CommonAPI::EmptyDeployment> deploy_error(static_cast< CommonAPI::EmptyDeployment * >(nullptr));
        CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_a(_a, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_b(_b, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< float, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< float, CommonAPI::EmptyDeployment >,
            CommonAPI::Deployable< float, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::DIVISION_ERROR, CommonAPI::EmptyDeployment>,
            CommonAPI::Deployable< float,CommonAPI::EmptyDeployment>
            >
            >::callMethodAsync(
        *this,
        "division",
        "dd",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_a, deploy_b,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< Calculator::DIVISION_ERROR, CommonAPI::EmptyDeployment > _deploy_error, CommonAPI::Deployable< float, CommonAPI::EmptyDeployment > _result) {
            if (_callback)
                _callback(_internalCallStatus, _deploy_error.getValue(), _result.getValue());
        },
        std::make_tuple(deploy_error, deploy_result));
    }
    /*
     * description: 
     * Perform Test1 operation.
     * (at)Return Test1 result.
     */
    void CalculatorDBusProxy::Test1(const uint8_t &_param, CommonAPI::CallStatus &_internalCallStatus, uint8_t &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment> deploy_param(_param, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint8_t,CommonAPI::EmptyDeployment>
            >
            >::callMethodWithReply(
        *this,
        "Test1",
        "y",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test1Async(const uint8_t &_param, Test1AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment> deploy_param(_param, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint8_t,CommonAPI::EmptyDeployment>
            >
            >::callMethodAsync(
        *this,
        "Test1",
        "y",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint8_t, CommonAPI::EmptyDeployment > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform Test2 operation.
     * (at)Return Test2 result.
     */
    void CalculatorDBusProxy::Test2(const uint16_t &_param, CommonAPI::CallStatus &_internalCallStatus, uint16_t &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint16_t, CommonAPI::EmptyDeployment> deploy_param(_param, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< uint16_t, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint16_t, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint16_t,CommonAPI::EmptyDeployment>
            >
            >::callMethodWithReply(
        *this,
        "Test2",
        "q",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test2Async(const uint16_t &_param, Test2AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint16_t, CommonAPI::EmptyDeployment> deploy_param(_param, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< uint16_t, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint16_t, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint16_t,CommonAPI::EmptyDeployment>
            >
            >::callMethodAsync(
        *this,
        "Test2",
        "q",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint16_t, CommonAPI::EmptyDeployment > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform Test3 operation.
     * (at)Return add result.
     */
    void CalculatorDBusProxy::Test3(const uint32_t &_param, CommonAPI::CallStatus &_internalCallStatus, uint32_t &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_param(_param, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_result(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint32_t,CommonAPI::DBus::IntegerDeployment>
            >
            >::callMethodWithReply(
        *this,
        "Test3",
        "u",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test3Async(const uint32_t &_param, Test3AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_param(_param, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
        CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment> deploy_result(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint32_t,CommonAPI::DBus::IntegerDeployment>
            >
            >::callMethodAsync(
        *this,
        "Test3",
        "u",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform Test4 operation.
     * (at)Return Test4 result.
     */
    void CalculatorDBusProxy::Test4(const uint64_t &_param, CommonAPI::CallStatus &_internalCallStatus, uint64_t &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint64_t, CommonAPI::EmptyDeployment> deploy_param(_param, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< uint64_t, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint64_t, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint64_t,CommonAPI::EmptyDeployment>
            >
            >::callMethodWithReply(
        *this,
        "Test4",
        "t",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test4Async(const uint64_t &_param, Test4AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< uint64_t, CommonAPI::EmptyDeployment> deploy_param(_param, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< uint64_t, CommonAPI::EmptyDeployment> deploy_result(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint64_t, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< uint64_t,CommonAPI::EmptyDeployment>
            >
            >::callMethodAsync(
        *this,
        "Test4",
        "t",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< uint64_t, CommonAPI::EmptyDeployment > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform Test5 operation.
     * (at)Return Test5 result.
     */
    void CalculatorDBusProxy::Test5(const std::string &_name, CommonAPI::CallStatus &_internalCallStatus, std::string &_message, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< std::string, CommonAPI::DBus::StringDeployment> deploy_name(_name, static_cast< CommonAPI::DBus::StringDeployment* >(nullptr));
        CommonAPI::Deployable< std::string, CommonAPI::DBus::StringDeployment> deploy_message(static_cast< CommonAPI::DBus::StringDeployment* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< std::string, CommonAPI::DBus::StringDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< std::string,CommonAPI::DBus::StringDeployment>
            >
            >::callMethodWithReply(
        *this,
        "Test5",
        "s",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_name,
_internalCallStatus,
deploy_message);
_message = deploy_message.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test5Async(const std::string &_name, Test5AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< std::string, CommonAPI::DBus::StringDeployment> deploy_name(_name, static_cast< CommonAPI::DBus::StringDeployment* >(nullptr));
        CommonAPI::Deployable< std::string, CommonAPI::DBus::StringDeployment> deploy_message(static_cast< CommonAPI::DBus::StringDeployment* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< std::string, CommonAPI::DBus::StringDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< std::string,CommonAPI::DBus::StringDeployment>
            >
            >::callMethodAsync(
        *this,
        "Test5",
        "s",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_name,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< std::string, CommonAPI::DBus::StringDeployment > _message) {
            if (_callback)
                _callback(_internalCallStatus, _message.getValue());
        },
        std::make_tuple(deploy_message));
    }
    /*
     * description: 
     * Perform Test6 operation.
     * (at)Return Test6 result.
     */
    void CalculatorDBusProxy::Test6(const Calculator::MetadataElement &_param, CommonAPI::CallStatus &_internalCallStatus, Calculator::MetadataElement &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MetadataElement, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MetadataElement, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MetadataElement, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MetadataElement,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t>
            >
            >::callMethodWithReply(
        *this,
        "Test6",
        "(iisu)",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test6Async(const Calculator::MetadataElement &_param, Test6AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MetadataElement, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MetadataElement, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MetadataElement, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MetadataElement,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t>
            >
            >::callMethodAsync(
        *this,
        "Test6",
        "(iisu)",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< Calculator::MetadataElement, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform Test7 operation.
     * (at)Return Test7 result.
     */
    void CalculatorDBusProxy::Test7(const Calculator::MetadataElementList &_param, CommonAPI::CallStatus &_internalCallStatus, Calculator::MetadataElementList &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MetadataElementList, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MetadataElementList, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MetadataElementList, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MetadataElementList,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t>
            >
            >::callMethodWithReply(
        *this,
        "Test7",
        "a(iisu)",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test7Async(const Calculator::MetadataElementList &_param, Test7AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MetadataElementList, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MetadataElementList, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MetadataElementList, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MetadataElementList,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t>
            >
            >::callMethodAsync(
        *this,
        "Test7",
        "a(iisu)",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< Calculator::MetadataElementList, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform Test8 operation.
     * (at)Return Test8 result.
     */
    void CalculatorDBusProxy::Test8(const Calculator::MyArray01 &_param, CommonAPI::CallStatus &_internalCallStatus, Calculator::MyArray01 &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MyArray01, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MyArray01, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray01, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray01,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t>
            >
            >::callMethodWithReply(
        *this,
        "Test8",
        "ay",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test8Async(const Calculator::MyArray01 &_param, Test8AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MyArray01, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MyArray01, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray01, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray01,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t>
            >
            >::callMethodAsync(
        *this,
        "Test8",
        "ay",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< Calculator::MyArray01, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform Test9 operation.
     * (at)Return Test9 result.
     */
    void CalculatorDBusProxy::Test9(const Calculator::MyArray02 &_param, CommonAPI::CallStatus &_internalCallStatus, Calculator::MyArray02 &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MyArray02, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MyArray02, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray02, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray02,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t>
            >
            >::callMethodWithReply(
        *this,
        "Test9",
        "aq",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test9Async(const Calculator::MyArray02 &_param, Test9AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MyArray02, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MyArray02, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray02, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray02,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t>
            >
            >::callMethodAsync(
        *this,
        "Test9",
        "aq",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< Calculator::MyArray02, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform Test10 operation.
     * (at)Return Test10 result.
     */
    void CalculatorDBusProxy::Test10(const Calculator::MyArray03 &_param, CommonAPI::CallStatus &_internalCallStatus, Calculator::MyArray03 &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MyArray03, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MyArray03, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray03, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray03,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t>
            >
            >::callMethodWithReply(
        *this,
        "Test10",
        "au",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test10Async(const Calculator::MyArray03 &_param, Test10AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MyArray03, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MyArray03, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray03, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray03,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t>
            >
            >::callMethodAsync(
        *this,
        "Test10",
        "au",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< Calculator::MyArray03, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform Test11 operation.
     * (at)Return Test11 result.
     */
    void CalculatorDBusProxy::Test11(const Calculator::MyArray04 &_param, CommonAPI::CallStatus &_internalCallStatus, Calculator::MyArray04 &_result, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MyArray04, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MyArray04, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray04, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray04,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t>
            >
            >::callMethodWithReply(
        *this,
        "Test11",
        "at",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_param,
_internalCallStatus,
deploy_result);
_result = deploy_result.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test11Async(const Calculator::MyArray04 &_param, Test11AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< Calculator::MyArray04, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t> deploy_param(_param, static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t* >(nullptr));
        CommonAPI::Deployable< Calculator::MyArray04, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t> deploy_result(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray04, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< Calculator::MyArray04,::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t>
            >
            >::callMethodAsync(
        *this,
        "Test11",
        "at",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_param,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< Calculator::MyArray04, ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t > _result) {
            if (_callback)
                _callback(_internalCallStatus, _result.getValue());
        },
        std::make_tuple(deploy_result));
    }
    /*
     * description: 
     * Perform Test12 operation.
     * (at)Return Test12 result.
     */
    void CalculatorDBusProxy::Test12(const CommonAPI::ByteBuffer &_name, CommonAPI::CallStatus &_internalCallStatus, CommonAPI::ByteBuffer &_message, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::EmptyDeployment> deploy_name(_name, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::EmptyDeployment> deploy_message(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< CommonAPI::ByteBuffer,CommonAPI::EmptyDeployment>
            >
            >::callMethodWithReply(
        *this,
        "Test12",
        "ay",
(_info ? _info : &CommonAPI::DBus::defaultCallInfo),
deploy_name,
_internalCallStatus,
deploy_message);
_message = deploy_message.getValue();
}
    std::future<CommonAPI::CallStatus> CalculatorDBusProxy::Test12Async(const CommonAPI::ByteBuffer &_name, Test12AsyncCallback _callback, const CommonAPI::CallInfo *_info) {
        CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::EmptyDeployment> deploy_name(_name, static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::EmptyDeployment> deploy_message(static_cast< CommonAPI::EmptyDeployment* >(nullptr));
        return CommonAPI::DBus::DBusProxyHelper<
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::EmptyDeployment >
            >,
            CommonAPI::DBus::DBusSerializableArguments<
            CommonAPI::Deployable< CommonAPI::ByteBuffer,CommonAPI::EmptyDeployment>
            >
            >::callMethodAsync(
        *this,
        "Test12",
        "ay",
        (_info ? _info : &CommonAPI::DBus::defaultCallInfo),
        deploy_name,
        [_callback] (CommonAPI::CallStatus _internalCallStatus, CommonAPI::Deployable< CommonAPI::ByteBuffer, CommonAPI::EmptyDeployment > _message) {
            if (_callback)
                _callback(_internalCallStatus, _message.getValue());
        },
        std::make_tuple(deploy_message));
    }


void CalculatorDBusProxy::getOwnVersion(uint16_t& ownVersionMajor, uint16_t& ownVersionMinor) const {
          ownVersionMajor = 1;
          ownVersionMinor = 0;
      }

      } // namespace CalculatorInterface
      } // namespace SimpleCalculator
      } // namespace v1
