/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201706201043.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/
/*
 * description: 
 * The interface provies APIs to perform calculator operations * author: 
 * Module Owner Name
 */
#ifndef V1_SIMPLECALCULATOR_CALCULATORINTERFACE_Calculator_DBUS_STUB_ADAPTER_HPP_
#define V1_SIMPLECALCULATOR_CALCULATORINTERFACE_Calculator_DBUS_STUB_ADAPTER_HPP_

#include <v1/SimpleCalculator/CalculatorInterface/CalculatorStub.hpp>
#include "v1/SimpleCalculator/CalculatorInterface/CalculatorDBusDeployment.hpp"
#include <v1/SimpleCalculator/CalculatorInterface/CalculatorDBusDeployment.hpp>

#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/DBus/DBusAddressTranslator.hpp>
#include <CommonAPI/DBus/DBusFactory.hpp>
#include <CommonAPI/DBus/DBusStubAdapterHelper.hpp>
#include <CommonAPI/DBus/DBusStubAdapter.hpp>
#include <CommonAPI/DBus/DBusDeployment.hpp>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace SimpleCalculator {
namespace CalculatorInterface {

template <typename _Stub = ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub, typename... _Stubs>
class CalculatorDBusStubAdapterInternal
    : public virtual CalculatorStubAdapter,
      public CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...>
     {
public:
    typedef CommonAPI::DBus::DBusStubAdapterHelper< _Stub, _Stubs...> CalculatorDBusStubAdapterHelper;

    ~CalculatorDBusStubAdapterInternal() {
        deactivateManagedInstances();
        CalculatorDBusStubAdapterHelper::deinit();
    }

    virtual bool hasFreedesktopProperties() {
        return false;
    }

    inline static const char* getInterface() {
        return Calculator::getInterface();
    }

    /*
     * description: 
     * This attribute reflects calculator operation value.
     */
    void fireCalattributeAttributeChanged(const int32_t& value);

    /*
     * description: 
     * This is a callback to update operation_status change.
     */
    void fireOperation_statusEvent(const uint32_t& status);

    void deactivateManagedInstances() {
    }

    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        CommonAPI::Version
        > getCalculatorInterfaceVersionStubDispatcher;

    /*
     * description: 
     * This attribute reflects calculator operation value.
     */
    static CommonAPI::DBus::DBusGetAttributeStubDispatcher<
            ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
            int32_t,
            CommonAPI::DBus::IntegerDeployment
            > getCalattributeAttributeStubDispatcher;
    static CommonAPI::DBus::DBusSetObservableAttributeStubDispatcher<
            ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
            int32_t,
            CommonAPI::DBus::IntegerDeployment
            > setCalattributeAttributeStubDispatcher;

    /*
     * description: 
     * Perform add operation.
     * (at)Return add result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< uint32_t, uint32_t>,
        std::tuple< uint32_t>,
        std::tuple< CommonAPI::DBus::IntegerDeployment, CommonAPI::DBus::IntegerDeployment>,
        std::tuple< CommonAPI::DBus::IntegerDeployment>
    
        > addStubDispatcher;

    /*
     * description: 
     * Perform divide operation.
     * (at)Return add result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< float, float>,
        std::tuple< Calculator::DIVISION_ERROR, float>,
        std::tuple< CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment>,
        std::tuple< CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment>
    
        > divisionStubDispatcher;

    /*
     * description: 
     * Perform Test1 operation.
     * (at)Return Test1 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< uint8_t>,
        std::tuple< uint8_t>,
        std::tuple< CommonAPI::EmptyDeployment>,
        std::tuple< CommonAPI::EmptyDeployment>
    
        > test1StubDispatcher;

    /*
     * description: 
     * Perform Test2 operation.
     * (at)Return Test2 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< uint16_t>,
        std::tuple< uint16_t>,
        std::tuple< CommonAPI::EmptyDeployment>,
        std::tuple< CommonAPI::EmptyDeployment>
    
        > test2StubDispatcher;

    /*
     * description: 
     * Perform Test3 operation.
     * (at)Return add result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< uint32_t>,
        std::tuple< uint32_t>,
        std::tuple< CommonAPI::DBus::IntegerDeployment>,
        std::tuple< CommonAPI::DBus::IntegerDeployment>
    
        > test3StubDispatcher;

    /*
     * description: 
     * Perform Test4 operation.
     * (at)Return Test4 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< uint64_t>,
        std::tuple< uint64_t>,
        std::tuple< CommonAPI::EmptyDeployment>,
        std::tuple< CommonAPI::EmptyDeployment>
    
        > test4StubDispatcher;

    /*
     * description: 
     * Perform Test5 operation.
     * (at)Return Test5 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< std::string>,
        std::tuple< std::string>,
        std::tuple< CommonAPI::DBus::StringDeployment>,
        std::tuple< CommonAPI::DBus::StringDeployment>
    
        > test5StubDispatcher;

    /*
     * description: 
     * Perform Test6 operation.
     * (at)Return Test6 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< Calculator::MetadataElement>,
        std::tuple< Calculator::MetadataElement>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t>
    
        > test6StubDispatcher;

    /*
     * description: 
     * Perform Test7 operation.
     * (at)Return Test7 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< Calculator::MetadataElementList>,
        std::tuple< Calculator::MetadataElementList>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t>
    
        > test7StubDispatcher;

    /*
     * description: 
     * Perform Test8 operation.
     * (at)Return Test8 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< Calculator::MyArray01>,
        std::tuple< Calculator::MyArray01>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t>
    
        > test8StubDispatcher;

    /*
     * description: 
     * Perform Test9 operation.
     * (at)Return Test9 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< Calculator::MyArray02>,
        std::tuple< Calculator::MyArray02>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t>
    
        > test9StubDispatcher;

    /*
     * description: 
     * Perform Test10 operation.
     * (at)Return Test10 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< Calculator::MyArray03>,
        std::tuple< Calculator::MyArray03>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t>
    
        > test10StubDispatcher;

    /*
     * description: 
     * Perform Test11 operation.
     * (at)Return Test11 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< Calculator::MyArray04>,
        std::tuple< Calculator::MyArray04>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t>,
        std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t>
    
        > test11StubDispatcher;

    /*
     * description: 
     * Perform Test12 operation.
     * (at)Return Test12 result.
     */
    
    static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        std::tuple< CommonAPI::ByteBuffer>,
        std::tuple< CommonAPI::ByteBuffer>,
        std::tuple< CommonAPI::EmptyDeployment>,
        std::tuple< CommonAPI::EmptyDeployment>
    
        > test12StubDispatcher;


    CalculatorDBusStubAdapterInternal(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
    : CommonAPI::DBus::DBusStubAdapter(_address, _connection,false),
      CalculatorDBusStubAdapterHelper(_address, _connection, false, _stub) {
        /*
         * description: 
         * This attribute reflects calculator operation value.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "getCalattributeAttribute", "" }, &getCalattributeAttributeStubDispatcher);
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "setCalattributeAttribute", "i" }, &setCalattributeAttributeStubDispatcher);
        /*
         * description: 
         * Perform add operation.
         * (at)Return add result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "add", "uu" }, &addStubDispatcher);
        /*
         * description: 
         * Perform divide operation.
         * (at)Return add result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "division", "dd" }, &divisionStubDispatcher);
        /*
         * description: 
         * Perform Test1 operation.
         * (at)Return Test1 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test1", "y" }, &test1StubDispatcher);
        /*
         * description: 
         * Perform Test2 operation.
         * (at)Return Test2 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test2", "q" }, &test2StubDispatcher);
        /*
         * description: 
         * Perform Test3 operation.
         * (at)Return add result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test3", "u" }, &test3StubDispatcher);
        /*
         * description: 
         * Perform Test4 operation.
         * (at)Return Test4 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test4", "t" }, &test4StubDispatcher);
        /*
         * description: 
         * Perform Test5 operation.
         * (at)Return Test5 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test5", "s" }, &test5StubDispatcher);
        /*
         * description: 
         * Perform Test6 operation.
         * (at)Return Test6 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test6", "(iisu)" }, &test6StubDispatcher);
        /*
         * description: 
         * Perform Test7 operation.
         * (at)Return Test7 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test7", "a(iisu)" }, &test7StubDispatcher);
        /*
         * description: 
         * Perform Test8 operation.
         * (at)Return Test8 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test8", "ay" }, &test8StubDispatcher);
        /*
         * description: 
         * Perform Test9 operation.
         * (at)Return Test9 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test9", "aq" }, &test9StubDispatcher);
        /*
         * description: 
         * Perform Test10 operation.
         * (at)Return Test10 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test10", "au" }, &test10StubDispatcher);
        /*
         * description: 
         * Perform Test11 operation.
         * (at)Return Test11 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test11", "at" }, &test11StubDispatcher);
        /*
         * description: 
         * Perform Test12 operation.
         * (at)Return Test12 result.
         */
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "Test12", "ay" }, &test12StubDispatcher);
        CalculatorDBusStubAdapterHelper::addStubDispatcher({ "getInterfaceVersion", "" }, &getCalculatorInterfaceVersionStubDispatcher);
    }

protected:
    virtual const char* getMethodsDBusIntrospectionXmlData() const {
        static const std::string introspectionData =
            "<method name=\"getInterfaceVersion\">\n"
                "<arg name=\"value\" type=\"uu\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"getCalattributeAttribute\">\n"
            "<arg name=\"value\" type=\"i\" direction=\"out\" />"
            "</method>\n"
            "<method name=\"setCalattributeAttribute\">\n"
            "<arg name=\"requestedValue\" type=\"i\" direction=\"in\" />\n"
            "<arg name=\"setValue\" type=\"i\" direction=\"out\" />\n"
            "</method>\n"
            "<signal name=\"onCalattributeAttributeChanged\">\n"
            "<arg name=\"changedValue\" type=\"i\" />\n"
            "</signal>\n"
            /*
             * description: 
             * This is a callback to update operation_status change.
             */
            "<signal name=\"operation_status\">\n"
            "<arg name=\"status\" type=\"u\" />\n"
            "</signal>\n"
            /*
             * description: 
             * Perform add operation.
             * (at)Return add result.
             */
            "<method name=\"add\">\n"
            "<arg name=\"_param1\" type=\"u\" direction=\"in\" />\n"
            "<arg name=\"_param2\" type=\"u\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"u\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform divide operation.
             * (at)Return add result.
             */
            "<method name=\"division\">\n"
            "<arg name=\"_a\" type=\"d\" direction=\"in\" />\n"
            "<arg name=\"_b\" type=\"d\" direction=\"in\" />\n"
            "<arg name=\"_error\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"_result\" type=\"d\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test1 operation.
             * (at)Return Test1 result.
             */
            "<method name=\"Test1\">\n"
            "<arg name=\"_param\" type=\"y\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"y\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test2 operation.
             * (at)Return Test2 result.
             */
            "<method name=\"Test2\">\n"
            "<arg name=\"_param\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"q\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test3 operation.
             * (at)Return add result.
             */
            "<method name=\"Test3\">\n"
            "<arg name=\"_param\" type=\"u\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"u\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test4 operation.
             * (at)Return Test4 result.
             */
            "<method name=\"Test4\">\n"
            "<arg name=\"_param\" type=\"t\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"t\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test5 operation.
             * (at)Return Test5 result.
             */
            "<method name=\"Test5\">\n"
            "<arg name=\"_name\" type=\"s\" direction=\"in\" />\n"
            "<arg name=\"_message\" type=\"s\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test6 operation.
             * (at)Return Test6 result.
             */
            "<method name=\"Test6\">\n"
            "<arg name=\"_param\" type=\"(iisu)\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"(iisu)\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test7 operation.
             * (at)Return Test7 result.
             */
            "<method name=\"Test7\">\n"
            "<arg name=\"_param\" type=\"a(iisu)\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"a(iisu)\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test8 operation.
             * (at)Return Test8 result.
             */
            "<method name=\"Test8\">\n"
            "<arg name=\"_param\" type=\"ay\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"ay\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test9 operation.
             * (at)Return Test9 result.
             */
            "<method name=\"Test9\">\n"
            "<arg name=\"_param\" type=\"aq\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"aq\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test10 operation.
             * (at)Return Test10 result.
             */
            "<method name=\"Test10\">\n"
            "<arg name=\"_param\" type=\"au\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"au\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test11 operation.
             * (at)Return Test11 result.
             */
            "<method name=\"Test11\">\n"
            "<arg name=\"_param\" type=\"at\" direction=\"in\" />\n"
            "<arg name=\"_result\" type=\"at\" direction=\"out\" />\n"
            "</method>\n"
            /*
             * description: 
             * Perform Test12 operation.
             * (at)Return Test12 result.
             */
            "<method name=\"Test12\">\n"
            "<arg name=\"_name\" type=\"ay\" direction=\"in\" />\n"
            "<arg name=\"_message\" type=\"ay\" direction=\"out\" />\n"
            "</method>\n"
            ;
        return introspectionData.c_str();
    }

private:
};


template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    CommonAPI::Version
    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::getCalculatorInterfaceVersionStubDispatcher(&CalculatorStub::getInterfaceVersion, "uu");

/*
 * description: 
 * This attribute reflects calculator operation value.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusGetAttributeStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        int32_t,
        CommonAPI::DBus::IntegerDeployment
        > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::getCalattributeAttributeStubDispatcher(
            &::v1::SimpleCalculator::CalculatorInterface::CalculatorStub::getCalattributeAttribute
            , "i"
            );
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusSetObservableAttributeStubDispatcher<
        ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
        int32_t,
        CommonAPI::DBus::IntegerDeployment
        > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::setCalattributeAttributeStubDispatcher(
                &::v1::SimpleCalculator::CalculatorInterface::CalculatorStub::getCalattributeAttribute,
                &CalculatorStubRemoteEvent::onRemoteSetCalattributeAttribute,
                &CalculatorStubRemoteEvent::onRemoteCalattributeAttributeChanged
                ,&CalculatorStubAdapter::fireCalattributeAttributeChanged
                ,"i"
                );


/*
 * description: 
 * Perform add operation.
 * (at)Return add result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< uint32_t, uint32_t>,
    std::tuple< uint32_t>,
    std::tuple< CommonAPI::DBus::IntegerDeployment, CommonAPI::DBus::IntegerDeployment>,
    std::tuple< CommonAPI::DBus::IntegerDeployment>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::addStubDispatcher(
    &CalculatorStub::add, "u",
    std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr), static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)));


/*
 * description: 
 * Perform divide operation.
 * (at)Return add result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< float, float>,
    std::tuple< Calculator::DIVISION_ERROR, float>,
    std::tuple< CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment>,
    std::tuple< CommonAPI::EmptyDeployment, CommonAPI::EmptyDeployment>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::divisionStubDispatcher(
    &CalculatorStub::division, "id",
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment * >(nullptr), static_cast< CommonAPI::EmptyDeployment* >(nullptr)));


/*
 * description: 
 * Perform Test1 operation.
 * (at)Return Test1 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< uint8_t>,
    std::tuple< uint8_t>,
    std::tuple< CommonAPI::EmptyDeployment>,
    std::tuple< CommonAPI::EmptyDeployment>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test1StubDispatcher(
    &CalculatorStub::Test1, "y",
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)));


/*
 * description: 
 * Perform Test2 operation.
 * (at)Return Test2 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< uint16_t>,
    std::tuple< uint16_t>,
    std::tuple< CommonAPI::EmptyDeployment>,
    std::tuple< CommonAPI::EmptyDeployment>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test2StubDispatcher(
    &CalculatorStub::Test2, "q",
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)));


/*
 * description: 
 * Perform Test3 operation.
 * (at)Return add result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< uint32_t>,
    std::tuple< uint32_t>,
    std::tuple< CommonAPI::DBus::IntegerDeployment>,
    std::tuple< CommonAPI::DBus::IntegerDeployment>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test3StubDispatcher(
    &CalculatorStub::Test3, "u",
    std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr)));


/*
 * description: 
 * Perform Test4 operation.
 * (at)Return Test4 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< uint64_t>,
    std::tuple< uint64_t>,
    std::tuple< CommonAPI::EmptyDeployment>,
    std::tuple< CommonAPI::EmptyDeployment>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test4StubDispatcher(
    &CalculatorStub::Test4, "t",
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)));


/*
 * description: 
 * Perform Test5 operation.
 * (at)Return Test5 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< std::string>,
    std::tuple< std::string>,
    std::tuple< CommonAPI::DBus::StringDeployment>,
    std::tuple< CommonAPI::DBus::StringDeployment>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test5StubDispatcher(
    &CalculatorStub::Test5, "s",
    std::make_tuple(static_cast< CommonAPI::DBus::StringDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::DBus::StringDeployment* >(nullptr)));


/*
 * description: 
 * Perform Test6 operation.
 * (at)Return Test6 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< Calculator::MetadataElement>,
    std::tuple< Calculator::MetadataElement>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test6StubDispatcher(
    &CalculatorStub::Test6, "(iisu)",
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t* >(nullptr)),
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementDeployment_t* >(nullptr)));


/*
 * description: 
 * Perform Test7 operation.
 * (at)Return Test7 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< Calculator::MetadataElementList>,
    std::tuple< Calculator::MetadataElementList>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test7StubDispatcher(
    &CalculatorStub::Test7, "a(iisu)",
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t* >(nullptr)),
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MetadataElementListDeployment_t* >(nullptr)));


/*
 * description: 
 * Perform Test8 operation.
 * (at)Return Test8 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< Calculator::MyArray01>,
    std::tuple< Calculator::MyArray01>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test8StubDispatcher(
    &CalculatorStub::Test8, "ay",
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t* >(nullptr)),
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray01Deployment_t* >(nullptr)));


/*
 * description: 
 * Perform Test9 operation.
 * (at)Return Test9 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< Calculator::MyArray02>,
    std::tuple< Calculator::MyArray02>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test9StubDispatcher(
    &CalculatorStub::Test9, "aq",
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t* >(nullptr)),
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray02Deployment_t* >(nullptr)));


/*
 * description: 
 * Perform Test10 operation.
 * (at)Return Test10 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< Calculator::MyArray03>,
    std::tuple< Calculator::MyArray03>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test10StubDispatcher(
    &CalculatorStub::Test10, "au",
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t* >(nullptr)),
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray03Deployment_t* >(nullptr)));


/*
 * description: 
 * Perform Test11 operation.
 * (at)Return Test11 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< Calculator::MyArray04>,
    std::tuple< Calculator::MyArray04>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t>,
    std::tuple< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test11StubDispatcher(
    &CalculatorStub::Test11, "at",
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t* >(nullptr)),
    std::make_tuple(static_cast< ::v1::SimpleCalculator::CalculatorInterface::Calculator_::MyArray04Deployment_t* >(nullptr)));


/*
 * description: 
 * Perform Test12 operation.
 * (at)Return Test12 result.
 */
template <typename _Stub, typename... _Stubs>
CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub,
    std::tuple< CommonAPI::ByteBuffer>,
    std::tuple< CommonAPI::ByteBuffer>,
    std::tuple< CommonAPI::EmptyDeployment>,
    std::tuple< CommonAPI::EmptyDeployment>

    > CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::test12StubDispatcher(
    &CalculatorStub::Test12, "ay",
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)),
    std::make_tuple(static_cast< CommonAPI::EmptyDeployment* >(nullptr)));

/*
 * description: 
 * This attribute reflects calculator operation value.
 */
template <typename _Stub, typename... _Stubs>
void CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::fireCalattributeAttributeChanged(const int32_t& value) {
    CommonAPI::Deployable< int32_t, CommonAPI::DBus::IntegerDeployment> deployedValue(value, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr));
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<
    CommonAPI::Deployable<
        int32_t,
        CommonAPI::DBus::IntegerDeployment
    >
    >>
        ::sendSignal(
            *this,
            "onCalattributeAttributeChanged",
            "i",
            deployedValue
    
    );
}

/*
 * description: 
 * This is a callback to update operation_status change.
 */
template <typename _Stub, typename... _Stubs>
void CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>::fireOperation_statusEvent(const uint32_t& status) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<
    CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment>
    >>::sendSignal(
            *this,
            "operation_status",
            "u",
    CommonAPI::Deployable< uint32_t, CommonAPI::DBus::IntegerDeployment>(status, static_cast< CommonAPI::DBus::IntegerDeployment* >(nullptr))
    );
}


template <typename _Stub = ::v1::SimpleCalculator::CalculatorInterface::CalculatorStub, typename... _Stubs>
class CalculatorDBusStubAdapter
    : public CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>,
      public std::enable_shared_from_this< CalculatorDBusStubAdapter<_Stub, _Stubs...>> {
public:
    CalculatorDBusStubAdapter(
        const CommonAPI::DBus::DBusAddress &_address,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection> &_connection,
        const std::shared_ptr<_Stub> &_stub)
        : CommonAPI::DBus::DBusStubAdapter(
            _address,
            _connection,
            false),
          CalculatorDBusStubAdapterInternal<_Stub, _Stubs...>(
            _address,
            _connection,
            _stub) {
    }
};

} // namespace CalculatorInterface
} // namespace SimpleCalculator
} // namespace v1

#endif // V1_SIMPLECALCULATOR_CALCULATORINTERFACE_Calculator_DBUS_STUB_ADAPTER_HPP_
