/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.dbus 3.1.12.v201706201043.
* Used org.franca.core 0.9.1.201412191134.
*
* This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
* If a copy of the MPL was not distributed with this file, You can obtain one at
* http://mozilla.org/MPL/2.0/.
*/

#ifndef V1_SIMPLECALCULATOR_CALCULATORINTERFACE_Calculator_DBUS_DEPLOYMENT_HPP_
#define V1_SIMPLECALCULATOR_CALCULATORINTERFACE_Calculator_DBUS_DEPLOYMENT_HPP_

#include <v1/SimpleCalculator/CalculatorInterface/CalculatorDBusDeployment.hpp>


#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif
#include <CommonAPI/DBus/DBusDeployment.hpp>
#undef COMMONAPI_INTERNAL_COMPILATION

namespace v1 {
namespace SimpleCalculator {
namespace CalculatorInterface {
namespace Calculator_ {

// Interface-specific deployment types
typedef CommonAPI::DBus::ArrayDeployment<
    CommonAPI::EmptyDeployment
> MyArray01Deployment_t;

typedef CommonAPI::DBus::ArrayDeployment<
    CommonAPI::EmptyDeployment
> MyArray02Deployment_t;

typedef CommonAPI::DBus::ArrayDeployment<
    CommonAPI::DBus::IntegerDeployment
> MyArray03Deployment_t;

typedef CommonAPI::DBus::ArrayDeployment<
    CommonAPI::EmptyDeployment
> MyArray04Deployment_t;

typedef CommonAPI::DBus::ArrayDeployment<
    CommonAPI::EmptyDeployment
> MyArray05Deployment_t;

typedef CommonAPI::DBus::StructDeployment<
    CommonAPI::EmptyDeployment,
    CommonAPI::EmptyDeployment,
    CommonAPI::DBus::StringDeployment,
    CommonAPI::DBus::IntegerDeployment
> MetadataElementDeployment_t;

typedef CommonAPI::DBus::ArrayDeployment<
    CommonAPI::DBus::StructDeployment<
        CommonAPI::EmptyDeployment,
        CommonAPI::EmptyDeployment,
        CommonAPI::DBus::StringDeployment,
        CommonAPI::DBus::IntegerDeployment
    >
> MetadataElementListDeployment_t;


// Type-specific deployments

// Attribute-specific deployments

// Argument-specific deployments

// Broadcast-specific deployments


} // namespace Calculator_
} // namespace CalculatorInterface
} // namespace SimpleCalculator
} // namespace v1

#endif // V1_SIMPLECALCULATOR_CALCULATORINTERFACE_Calculator_DBUS_DEPLOYMENT_HPP_
